package pt.isel.vsddashboardapplication.repository.pojo.statistics

import com.squareup.moshi.Json

data class DpiFlowstats(
    @Json(name = "APMGroup") val aPMGroup: String? = "",
    @Json(name = "AppGroupID") val appGroupID: String? = "",
    @Json(name = "AppID") val appID: String? = "",
    @Json(name = "Application") val application: String? = "",
    @Json(name = "CommonName") val commonName: String? = "",
    @Json(name = "DestinationNSG") val destinationNSG: String? = "",
    @Json(name = "Domain") val domain: String? = "",
    @Json(name = "DstIp") val dstIp: String? = "",
    @Json(name = "DstNSG") val dstNSG: String? = "",
    @Json(name = "DstPort") val dstPort: Int? = 0,
    @Json(name = "DstUplink") val dstUplink: String? = "",
    @Json(name = "DstUplinkIndex") val dstUplinkIndex: String? = "",
    @Json(name = "DstUplinkRole") val dstUplinkRole: String? = "",
    @Json(name = "EgressBytes") val egressBytes: Int? = 0,
    @Json(name = "EgressMB") val egressMB: Double? = 0.0,
    @Json(name = "EgressPackets") val egressPackets: Int? = 0,
    @Json(name = "EnterpriseName") val enterpriseName: String? = "",
    @Json(name = "EvpnID") val evpnID: Int? = 0,
    @Json(name = "HasSwitchedPaths") val hasSwitchedPaths: String? = "",
    @Json(name = "IngressBytes") val ingressBytes: Int? = 0,
    @Json(name = "IngressMB") val ingressMB: Double? = 0.0,
    @Json(name = "IngressPackets") val ingressPackets: Int? = 0,
    @Json(name = "L7ClassEnhanced") val l7ClassEnhanced: String? = "",
    @Json(name = "L7Classification") val l7Classification: String? = "",
    @Json(name = "Proto") val proto: String? = "",
    @Json(name = "SlaStatus") val slaStatus: String? = "",
    @Json(name = "SourceNSG") val sourceNSG: String? = "",
    @Json(name = "SrcIp") val srcIp: String? = "",
    @Json(name = "SrcNSG") val srcNSG: String? = "",
    @Json(name = "SrcPort") val srcPort: Int? = 0,
    @Json(name = "SrcUplink") val srcUplink: String? = "",
    @Json(name = "SrcUplinkIndex") val srcUplinkIndex: String? = "",
    @Json(name = "SrcUplinkRole") val srcUplinkRole: String? = "",
    @Json(name = "SrcVportName") val srcVportName: String? = "",
    @Json(name = "SrcVportUUID") val srcVportUUID: String? = "",
    @Json(name = "timestamp") val timestamp: Long? = 0,
    @Json(name = "TotalBytesCount") val totalBytesCount: Int? = 0,
    @Json(name = "TotalMB") val totalMB: Double? = 0.0,
    @Json(name = "TotalPacketsCount") val totalPacketsCount: Int? = 0,
    @Json(name = "UnderlayID") val underlayID: Int? = 0,
    @Json(name = "UnderlayName") val underlayName: String? = "",
    @Json(name = "VrfID") val vrfID: Int? = 0
)